import json
import click
from openai import OpenAI
from mridicomsort.config import LLM_API_KEY, MODEL_NAME, LLM_BASE_URL

# Initialize the OpenAI client
client = OpenAI(api_key=LLM_API_KEY, base_url=LLM_BASE_URL)


def normalize_sequences(sequence_list: list, model_name: str = MODEL_NAME) -> dict:
    """Calls OpenAI to generate a normalized mapping for a list of MRI sequences."""

    prompt = f"""
    You are an expert Radiologic Technologist in MRI.
    You will have a list of raw MRI contrast-weighting sequence strings that contain
    inconsistent naming conventions, typos, and vendor-specific shorthand. Your goal is
    to consolidate these into a clean, standardized list of meaningful clinical labels.
    
    1. Group by Contrast & Technique.
    2. Handle Synonyms: Treat "Ultra_Fast," "Turbo," and "Fast" as the same functional
    category unless otherwise specified.
    3. Ignore Formatting: Ignore case sensitivity, underscores, hyphens, and trailing spaces
    (e.g., T2_GRE and T2-gre are the same).
    4. DWI Specifics: Group all Diffusion-weighted variations (EPI, Multi-b) under a unified
    "DWI".
    
    Output Format:
    Return a JSON object. {{"Old_Name":"New_Name"}}
    Examples: {{"T1_Ultra_fast_GRE": "T1_GRE", "T2_UltraFastSE": "T2_SE"}}
    
    Input List:
    {json.dumps(sequence_list, indent=2)}
    """

    try:
        response = client.chat.completions.create(
            model=model_name,
            messages=[
                {
                    "role": "system",
                    "content": "You are a helpful assistant designed to output strictly valid JSON.",
                },
                {"role": "user", "content": prompt},
            ],
            temperature=0.0,
            # Enforce JSON output for newer OpenAI models
            response_format={"type": "json_object"},
        )

        result_str = response.choices[0].message.content.strip()
        return json.loads(result_str)

    except Exception as e:
        print(f"Error calling OpenAI: {e}")
        return {}
    
def clean_modality_name(name: str) -> str:

    if "<unused95>" in name.lower():
        name = name.split("<unused95>")[1].strip()
    return name.strip().upper().replace(" ", "_").replace("-", "_")


def collect_names(node: dict, names_set: set):
    """Recursively extracts all unique cluster_names from the tree."""
    if "cluster_name" in node:      
            names_set.add(clean_modality_name(node["cluster_name"]))
    elif "branches" in node:
        for child in node["branches"].values():
            collect_names(child, names_set)


def apply_mapping(node: dict, mapping: dict):
    """Recursively updates cluster_names in the tree based on the LLM mapping."""
    if "cluster_name" in node:
        old_name = node["cluster_name"]
        cleaned_old_name = clean_modality_name(old_name)
       
        node["cluster_name"] = mapping.get(cleaned_old_name, cleaned_old_name)
    elif "branches" in node:
        for child in node["branches"].values():
            apply_mapping(child, mapping)


@click.command()
@click.argument("input_tree", type=click.Path(exists=True, dir_okay=False))
@click.option(
    "--output",
    type=click.Path(file_okay=True),
    default="normalized_dicom_clusters.json",
    help="Path to save the newly normalized JSON tree.",
)
@click.option(
    "--save-mapping",
    type=click.Path(file_okay=True),
    default="modality_mapping.json",
    help="Path to save the raw dictionary mapping generated by the LLM.",
)
def main(input_tree, output, save_mapping):
    print(f"Loading cluster tree from {input_tree}...")
    with open(input_tree, "r") as f:
        tree = json.load(f)

    # 1. Traverse the tree to find all unique modalities
    unique_modalities = set()
    collect_names(tree, unique_modalities)
    modality_list = list(unique_modalities)

    if not modality_list:
        print("No 'cluster_name' fields found in the provided JSON tree. Exiting.")
        return

    print(
        f"Found {len(modality_list)} unique modalities. Contacting OpenAI for normalization..."
    )

    # 2. Call the LLM to get the cleaned mapping dictionary
    mapping = normalize_sequences(modality_list)

    if not mapping:
        print("Failed to generate a valid mapping from the LLM. Exiting.")
        return

    print("\nNormalization mapping generated:")
    print(json.dumps(mapping, indent=2))

    # 3. Save the mapping for your records/debugging
    with open(save_mapping, "w") as f:
        json.dump(mapping, f, indent=2)
    print(f"\nSaved mapping reference to {save_mapping}")

    # 4. Apply the mapping to overwrite the messy names in the tree
    print("Applying mapping to the tree...")
    apply_mapping(tree, mapping)

    # 5. Save the updated tree
    with open(output, "w") as f:
        json.dump(tree, f, indent=2)

    print(f"Done! Normalized tree saved to {output}.")


if __name__ == "__main__":
    main()